### ISSUE TITLE
define baseline of input fields

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#62] opened 2015-03-10 01:56 UTC

**Comment by dviramontes** [comment] 2015-03-11 23:41
possible duplicate of #63 ?

**Comment by hasuf** [comment] 2015-03-12 17:46
Hi @dviramontes... At the time we created these, we recognized that they would be very closely related. I guess #63  could be looked upon as a subtask of this one.

**Comment by switzersc** [comment] 2015-03-31 01:53
does anyone remember what this is related to?

**Closed as completed** 2015-03-31 02:19 UTC
Labels: intake
